name: Publish to NPM

on:
  push:
    paths:
      - 'index.js'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prepare git and update version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm run auto-version
          git commit -m "tags: updated tags" -a

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
